### ISSUE TITLE
unsigned integer overflow in CAuxPow::getExpectedIndex

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#391]
An unsigned integer overflow (which is undefined behavior in C++) exists in `CAuxPow::getExpectedIndex` in the `auxpow` branch.

**Expected behavior**

The `check_auxpow` test case should pass.

**Actual behavior**

~~~
�[0;39;49m�[1;34;49mtest/auxpow_tests.cpp(237): Entering test case "check_auxpow"
auxpow.cpp:139:15: runtime error: unsigned integer overflow: 7 * 1103515245 cannot be represented in type 'unsigned int'
    #0 0x563e8c5b07fa in CAuxPow::getExpectedIndex(unsigned int, int, unsigned int) /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/auxpow.cpp:139:15
    #1 0x563e8afc2d8e in auxpow_tests::check_auxpow::test_method() /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/auxpow_tests.cpp:253:11
    #2 0x563e8afc160f in auxpow_tests::check_auxpow_invoker() /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/auxpow_tests.cpp:237:1
    #3 0x563e8aedd9dc in boost::detail::function::void_function_invoker0<void (*)(), void>::invoke(boost::detail::function::function_buffer&) /usr/include/boost/function/function_template.hpp:117:11
    #4 0x7f17307a73f1  (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x353f1)
    #5 0x7f17307a4c74 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x32c74)
    #6 0x7f17307a4cf7 in boost::execution_monitor::execute(boost::function<int ()> const&) (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x32cf7)
    #7 0x7f17307a4dcd in boost::execution_monitor::vexecute(boost::function<void ()> const&) (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x32dcd)
    #8 0x7f17307d2134 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned long) (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x60134)
    #9 0x7f17307b55a8  (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x435a8)
    #10 0x7f17307b5b03  (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x43b03)
    #11 0x7f17307b5b03  (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x43b03)
    #12 0x7f17307ac939 in boost::unit_test::framework::run(unsigned long, bool) (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x3a939)
    #13 0x7f17307d0fea in boost::unit_test::unit_test_main(bool (*)(), int, char**) (/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0+0x5efea)
    #14 0x563e8ae2427a in main /usr/include/boost/test/unit_test.hpp:63:12
    #15 0x7f172fe300b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #16 0x563e8ad79a7d in _start (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/test/test_bitcoin+0x252ca7d)

SUMMARY: UndefinedBehaviorSanitizer: unsigned-integer-overflow auxpow.cpp:139:15 in 
make[3]: *** [Makefile:16832: test/auxpow_tests.cpp.test] Error 1
~~~

**To reproduce**

Run the `[no depends, sanitizers: address/leak (ASan + LSan) + undefined (UBSan) + integer] [focal]` task for the `auxpow` branch on Cirrus.  Example run at https://github.com/namecoin/namecoin-core/runs/1680144667

**System information**

Git commit hash 55979b89fe77e2420e924a176e151d61644a4a0d , built on Cirrus CI.

**Comment by domob1812** [comment]
Probably easy to fix.  I will check it out together with next week's merges.

**Comment by domob1812** [comment]
Has been fixed (see e.g. https://cirrus-ci.com/task/4768051063160832).
