### ISSUE TITLE
feature_pruning functional tests failing

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#397]
The `feature_pruning.py` functional tests are failing.

**Expected behavior**

Functional tests should pass.

**Actual behavior**

~~~
1/197 - feature_pruning.py failed, Duration: 11 s
stdout:
2021-01-21T07:56:15.045000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210121_075611/feature_pruning_196
2021-01-21T07:56:17.434000Z TestFramework (INFO): Warning! This test requires 4GB of disk space
2021-01-21T07:56:17.434000Z TestFramework (INFO): Mining a big blockchain of 995 blocks
2021-01-21T07:56:25.027000Z TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_pruning.py", line 347, in run_test
    self.create_big_chain()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_pruning.py", line 122, in create_big_chain
    mine_large_blocks(self.nodes[0], 645)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_pruning.py", line 65, in mine_large_blocks
    node.submitblock(ToHex(block))
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/messages.py", line 210, in ToHex
    return obj.serialize().hex()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/messages.py", line 752, in serialize
    r += super().serialize()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/messages.py", line 711, in serialize
    r += self.auxpow.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'
2021-01-21T07:56:25.079000Z TestFramework (INFO): Stopping nodes
2021-01-21T07:56:25.434000Z TestFramework (WARNING): Not cleaning up dir /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210121_075611/feature_pruning_196
2021-01-21T07:56:25.434000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210121_075611/feature_pruning_196/test_framework.log
2021-01-21T07:56:25.435000Z TestFramework (ERROR): 
2021-01-21T07:56:25.435000Z TestFramework (ERROR): Hint: Call /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/combine_logs.py '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210121_075611/feature_pruning_196' to consolidate all logs
2021-01-21T07:56:25.435000Z TestFramework (ERROR): 
2021-01-21T07:56:25.435000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2021-01-21T07:56:25.435000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2021-01-21T07:56:25.435000Z TestFramework (ERROR): 
~~~

See https://cirrus-ci.com/task/6639907902849024 for an example.

**To reproduce**

Run the `[previous releases, uses qt5 dev package and some depends packages] [unsigned char] [bionic]` Cirrus task.

**System information**

Namecoin Core `auxpow` branch, commit hash 8e81ee2da2e396a9bb61d0a645a444521397b831, on Cirrus.

**Comment by domob1812** [comment]
I can take a look at some point.  I guess this is one of the tests that is not run by default (since it needs so much disk space).
