### ISSUE TITLE
testscript txn_clone.py fails sometimes

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-core#79]
Fails for the "32-bit + dash" instance on Travis CI, but works fine on the "bitcoind" instance.

This is in the master branch.  Seems to have been introduced between https://github.com/namecoin/namecoin-core/commit/3dea37f36559a5e529df405ffbe819441ead6d90 and https://github.com/namecoin/namecoin-core/commit/f55f25bd4cb9598dded524feb6803ff54570db5e .  auxpow branch and 0.12 branch are unaffected.

Error log:

Running testscript [1mtxn_clone.py[0m ...
Initializing test directory /tmp/testWrdRT7
start_node: namecoind started, calling namecoin-cli -rpcwait getblockcount
start_node: calling namecoin-cli -rpcwait getblockcount returned
start_node: namecoind started, calling namecoin-cli -rpcwait getblockcount
start_node: calling namecoin-cli -rpcwait getblockcount returned
start_node: namecoind started, calling namecoin-cli -rpcwait getblockcount
start_node: calling namecoin-cli -rpcwait getblockcount returned
start_node: namecoind started, calling namecoin-cli -rpcwait getblockcount
start_node: calling namecoin-cli -rpcwait getblockcount returned
JSONRPC error: 66: insufficient priority
  File "/home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/test_framework/test_framework.py", line 146, in main
    self.run_test()
  File "/home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/txn_clone.py", line 107, in run_test
    txid1_clone = self.nodes[2].sendrawtransaction(tx1_clone["hex"])
  File "/home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/test_framework/coverage.py", line 50, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/test_framework/authproxy.py", line 140, in __call__
    raise JSONRPCException(response['error'])
Stopping nodes
Cleaning up
Failed
Traceback (most recent call last):
  File "qa/pull-tester/rpc-tests.py", line 285, in <module>
    runtests()
  File "qa/pull-tester/rpc-tests.py", line 185, in runtests
    rpcTestDir + testScripts[i] + flags, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/qa/rpc-tests/txn_clone.py --srcdir /home/travis/build/namecoin/namecoin-core/bitcoin-i686-pc-linux-gnu/src --coveragedir /tmp/coverage2amTgl ' returned non-zero exit status 1

**Comment by domob1812** [comment]
Could have been fixed by the latest upstream patch merges (where I also included a change to up the tx fee in the test since it failed for me as well).

**Comment by JeremyRand** [comment]
Confirmed as fixed, thanks.  Closing.
